### ISSUE TITLE
Cannot complete initial setup (wrong field validation?)

### ISSUE THREAD

**Issue by paulvt** [black-sheep-dev/harbour-quartermaster#9]
I just upgraded to Quartermaster 0.2.1, but I cannot complete the initial setup that needs to be redone.

For the "Connection Settings" step it says I should fill in a hostname or IP-address in the local network. However, if I enter a hostname or IP address in the Hostname field, the value is considered invalid ("Valid hostname or IP required")? It reallly seems to want an URL in the hostname field? But that makes the Port field weird. I'm guessing the validation for the Hostname field is set incorrectly?

If I do enter the URL (http://something.local.domain) in the Hostname field, the Connect becomes available, but when pressing it I get for Connection Infos: "Failed to connect to server. Go back and check your data".

Also, I don't want to use an internal URL with HTTP at all! Even though traffic goes over a local network, HTTP is still not recommended and to use HTTPS internally is really a hassle given that the hostname should be validatable by Let's Encrypt so I always use my external URL.

**Comment by black-sheep-dev** [comment]
Thanks for your feedback!

You can also use your external address for this step.

The idea behind connecting over local network first is that you sit at home when doing this. Home Assistant API will provide the external address later on (when configured in configuration.yaml). Then you are able to switch between these in the next step of the setup wizard. 

In the developer documentation of Home Assistant API they recommend to use local address when at home, because some routers can not handle it otherwise.

The field needs an url ( e.g. http://server.local / https://homenet.example.org ). Otherwise I don't know when to use ssl
Home Assistant API provides also full urls. The ports need to be handled separately (not provided by API).
You can use https locally when your Home Assistant is configured to use it.

But you are right, there is a bug with the hostname validation when using an IP address. I will fix this in the next release.

**Comment by paulvt** [comment]
Ah ok, so the Hostname fields are actuall URI fields, but without the port.

Yes, maybe the text on the initial "Connection Settings" step should be changed to indicate both URLs are supported.

**Comment by paulvt** [comment]
Note that as I fill in the Internal URL and External URL, and successfully connect with the long-lived token, these URLs are not shown in the summary with Informations and Configuration checks.

(Also the text labels mention information**s**/info**s**, but information has no plural in English.)

**Comment by paulvt** [comment]
Finally I end up with the error:

```
Registration failed
Protocol "" is unknown.
```

Can I debug this somehow? This seems related to the Internal/External URL showing as not filled in, because if I go back, they are empty again?

**Comment by paulvt** [comment]
Aaah, I found out what is going on here. In my Home Assistant the External/Internal URL are not configured. This is because most stuff is in `configuration.yml` and I did that years ago. So, after the initial steps, it seems Quartermaster retrieves data from my HA instance, and replaces the earlier filled in external & internal URL with the empty values it got. Thus blocking the initial setup progress.

So I configured the internal/external URL in HA properly now. But found out that these URLs should be without port as well, because otherwise Quatermaster will try to connect to `https://host.domain.tld:8124` port 8124, which, again, fails. Why not go for full URLs and drop the Port fields as well? I think my External/Internal URLs should contain them in HA?

**Comment by black-sheep-dev** [comment]
Thanks for the info!

I checked the Home Assistant documentation and it says that the internal and external url can be provided with protocol://hostname:port. So the should be configured in Home Assistant
I will change this to a full url input instead. Also I need to handle the situation that internal and external url is not configured in Home Assistant.

**Comment by paulvt** [comment]
Glad to be of help! I know itt is hard to catch all these side cases in one go in the initial setup, as everyone probably only goes through it once (or twice now with 0.2) :wink:.

**Comment by black-sheep-dev** [comment]
Changed everything relating to connection details to full URL input instead off hostame / port with 0.2.4.
